@SSI.Extensions.Logging.TracesOnError.EnrichExisting_HostAddress = http://localhost:5051

GET {{SSI.Extensions.Logging.TracesOnError.EnrichExisting_HostAddress}}/weatherforecast/
Accept: application/json

###
