@SSI.Extensions.Logging.TracesOnError.ApplicationInsights_HostAddress = http://localhost:5147

GET {{SSI.Extensions.Logging.TracesOnError.ApplicationInsights_HostAddress}}/weatherforecast/
Accept: application/json

###
